### ISSUE TITLE
launch ai worker failed: Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38"

### ISSUE THREAD

**Issue by flyworker** [nebulaai/ai-worker#1]
$ ./launch_nbai_worker 
time="2019-03-06 17:01:11" level=error message="Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38"

**Comment by dcutugno** [comment]
updating ubuntu can give the error above a re-run of install.sh and a try with this command can solve the problem:
sudo apt-get install docker-ce=5:18.09.2~3-0~ubuntu-bionic docker-ce-cli=5:18.09.2~3-0~ubuntu-bionic

**Comment by flyworker** [comment]
Close as it is resolved.
